name: Checks and tests

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint --rcfile=.pylintrc */**.py
        poetry run pylint tests --rcfile=.pylintrc.tests
    - name: Running tests
      run: |
        poetry run pytest -v
    - name: Check types
      run: |
        poetry run mypy glampy
    - name: Check formatting
      run: |
        poetry run black --check .
