name: Create Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # TODO: allow only semver tags in a strict way

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
      # TODO: use changelog for body
      #   bodyFile: "body.md"
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
